-- Run once in the Supabase SQL editor to enable report-ID lookups.

create table if not exists public.generated_reports (
  id bigint generated by default as identity primary key,
  report_id text not null unique,
  report_type text not null,       -- 'approval' | 'specialty_general' | 'specialty_custom'
  staff_id text,
  staff_name text,
  generated_at timestamptz not null default now(),
  details jsonb
);

create index if not exists generated_reports_report_id_idx
  on public.generated_reports (report_id);

-- This app uses its own custom auth (not Supabase Auth), so the anon key
-- needs a permissive policy to insert/select — same pattern your other
-- tables (Companies, vendor_tags, etc.) already use.
alter table public.generated_reports enable row level security;

create policy "Allow all access to generated_reports"
on public.generated_reports
for all
using (true)
with check (true);
