-- Vendor COI expiration email reminders -- EMPLOYEE-facing notifications
-- only (a separate vendor-facing email was discussed but is explicitly
-- out of scope for this piece -- Coleby asked to focus on the employee
-- side first, 2026-09-04).
--
-- Four notification "phases", checked once a day by a scheduled Supabase
-- Edge Function (see supabase/functions/send-coi-reminders/index.ts):
--   60_day         -- fires once per expiration date, the first day a COI
--                     has 60 days or less left (and more than 30)
--   30_day         -- fires once per expiration date, the first day a COI
--                     has 30 days or less left (and more than 7)
--   7_day_daily    -- fires every day while a COI has between 0 and 7 days
--                     left (0 = expires today)
--   expired_daily  -- fires every day once a COI's expiration date has
--                     fully passed (1+ days overdue)
--
-- 60_day/30_day fire on "<= N days left" rather than "exactly N days left"
-- so a day the cron doesn't run (deploy hiccup, etc.) doesn't silently
-- skip a vendor's reminder for the rest of that cycle -- it just catches
-- up next time the job runs. coi_notification_log below makes sure that
-- still only happens once per expiration date; uploading a renewed COI
-- with a new date naturally resets it, since the log is keyed to the old
-- date.
--
-- Recipients are plain email addresses, not staff accounts. staff_users'
-- only stored "email" (auth_email) is a synthetic, never-shown address
-- that exists purely to satisfy Supabase Auth's login requirement (see
-- migrate-staff-to-auth.ts's AUTH_EMAIL_DOMAIN) -- not a real inbox, so
-- there's nothing real to pick from there today. If real staff email
-- addresses get added to this app later, the settings UI can be swapped
-- for a staff picker without touching the sending logic in the Edge
-- Function at all (it just reads whatever's in recipient_emails).
--
-- Settings visible/editable by IT or Super Admin only, per Coleby's
-- instruction (2026-09-04) -- same is_workgroup('IT')/is_super_admin()
-- gate already used for the Workgroups page and the audit log in
-- supabase-rls-lockdown.sql.
--
-- Run this once in the Supabase SQL Editor.

/* ===========================
   SETTINGS -- one row per phase, holding who gets notified for it.
   Seeded with all four phases so the UI always has something to load
   and update (never has to "create" a phase row itself).
=========================== */

create table if not exists public.coi_notification_settings (
  phase text primary key check (phase in ('60_day', '30_day', '7_day_daily', 'expired_daily')),
  recipient_emails text[] not null default '{}',
  updated_at timestamptz not null default now(),
  updated_by uuid references public.staff_users(id)
);

insert into public.coi_notification_settings (phase)
values ('60_day'), ('30_day'), ('7_day_daily'), ('expired_daily')
on conflict (phase) do nothing;

/* ===========================
   SEND LOG -- prevents duplicate sends. Written only by the Edge Function
   via the service-role key (bypasses RLS), never by the client.

   IMPORTANT -- company_id is typed `bigint` to match public."Companies".id
   as used elsewhere (see supabase-vendor-tags-setup.sql's company_tags
   table, which has the identical caveat comment). If that column turns
   out to actually be uuid, change the type below before running this file.
=========================== */

create table if not exists public.coi_notification_log (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public."Companies"(id) on delete cascade,
  phase text not null check (phase in ('60_day', '30_day', '7_day_daily', 'expired_daily')),
  coi_expires_on date not null,
  sent_on date not null default current_date,
  created_at timestamptz not null default now(),
  unique (company_id, phase, coi_expires_on, sent_on)
);

create index if not exists coi_notification_log_lookup_idx
  on public.coi_notification_log (company_id, phase, coi_expires_on);

/* ===========================
   ACCESS -- IT / Super Admin only
=========================== */

create or replace function public.has_coi_notification_access()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.is_workgroup('IT') or public.is_super_admin();
$$;

grant execute on function public.has_coi_notification_access() to authenticated;

alter table public.coi_notification_settings enable row level security;
alter table public.coi_notification_log enable row level security;

drop policy if exists "coi_notification_settings_it_admin" on public.coi_notification_settings;
create policy "coi_notification_settings_it_admin" on public.coi_notification_settings
  for all to authenticated
  using (public.has_coi_notification_access())
  with check (public.has_coi_notification_access());

-- Read-only for IT/Super Admin, mainly so send history can be inspected
-- from the client if that's ever useful for debugging a "didn't get the
-- email" report. All writes happen server-side via the service-role key.
drop policy if exists "coi_notification_log_it_admin_read" on public.coi_notification_log;
create policy "coi_notification_log_it_admin_read" on public.coi_notification_log
  for select to authenticated
  using (public.has_coi_notification_access());
