/* ============================================================================
   supabase-vendor-tags-setup.sql
   Adds two tag groups to the Vendors (Companies) page: "Asset Specialty" and
   "Trade". A vendor can carry any number of tags from either group.

   IMPORTANT — check this before running:
   company_tags.company_id below is typed `bigint`, which matches the default
   PK type Supabase's Table Editor gives a table (bigint generated by default
   as identity). If your public."Companies".id column is actually a uuid (or
   anything else), change the `company_id bigint` line below to match before
   running this file, or the foreign key will fail to create.

   Design notes:
   - Tag categories ("Asset Specialty", "Trade") live in a real table rather
     than a hardcoded list/enum, so a third category can be added later with
     a plain insert — no code or schema change needed.
   - vendor_tags holds the individual tag values under each category (e.g.
     "Framing Labor" under "Trade").
   - company_tags is the many-to-many join between Companies and vendor_tags,
     so each vendor can have multiple tags per category.
   - RLS follows this app's established pattern: the app uses custom auth
     (not Supabase Auth), so auth.uid() is always null server-side. Access
     control is enforced in the JS/UI layer, and RLS here is permissive to
     the anon role, matching every other table in this project.
============================================================================ */

create table if not exists public.vendor_tag_categories (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.vendor_tags (
  id uuid primary key default gen_random_uuid(),
  category_id uuid not null references public.vendor_tag_categories(id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now(),
  unique (category_id, name)
);

create table if not exists public.company_tags (
  id uuid primary key default gen_random_uuid(),
  company_id bigint not null references public."Companies"(id) on delete cascade,
  tag_id uuid not null references public.vendor_tags(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (company_id, tag_id)
);

create index if not exists company_tags_company_id_idx on public.company_tags(company_id);
create index if not exists company_tags_tag_id_idx on public.company_tags(tag_id);
create index if not exists vendor_tags_category_id_idx on public.vendor_tags(category_id);

/* ===========================
   RLS — permissive to anon, matching the rest of this app
=========================== */

alter table public.vendor_tag_categories enable row level security;
alter table public.vendor_tags enable row level security;
alter table public.company_tags enable row level security;

do $$
declare
  t text;
begin
  foreach t in array array['vendor_tag_categories', 'vendor_tags', 'company_tags']
  loop
    execute format('drop policy if exists "%1$s_anon_select" on public.%1$s;', t);
    execute format('drop policy if exists "%1$s_anon_insert" on public.%1$s;', t);
    execute format('drop policy if exists "%1$s_anon_update" on public.%1$s;', t);
    execute format('drop policy if exists "%1$s_anon_delete" on public.%1$s;', t);

    execute format('create policy "%1$s_anon_select" on public.%1$s for select using (true);', t);
    execute format('create policy "%1$s_anon_insert" on public.%1$s for insert with check (true);', t);
    execute format('create policy "%1$s_anon_update" on public.%1$s for update using (true) with check (true);', t);
    execute format('create policy "%1$s_anon_delete" on public.%1$s for delete using (true);', t);
  end loop;
end $$;

/* ===========================
   SEED DATA — the two categories + starting tag lists.
   Safe to re-run: everything uses ON CONFLICT DO NOTHING.
=========================== */

insert into public.vendor_tag_categories (name, sort_order) values
  ('Asset Specialty', 1),
  ('Trade', 2)
on conflict (name) do nothing;

insert into public.vendor_tags (category_id, name)
select (select id from public.vendor_tag_categories where name = 'Asset Specialty'), t.name
from (values
  ('General Construction'),
  ('Residential'),
  ('Multi Family'),
  ('Flex Space')
) as t(name)
on conflict (category_id, name) do nothing;

insert into public.vendor_tags (category_id, name)
select (select id from public.vendor_tag_categories where name = 'Trade'), t.name
from (values
  ('Const. Clean - Interior'),
  ('Const. Clean - Site'),
  ('Const. Clean - Site Labor Misc'),
  ('Const. Clean - Supplies'),
  ('Construction Trash'),
  ('Plan Reprographics'),
  ('Portolets'),
  ('Street Sweeping'),
  ('Survey/Staking - Constru'),
  ('Temporary Electric'),
  ('Temporary Water'),
  ('Third Party Inspections'),
  ('Vendor Appreciation'),
  ('Concrete'),
  ('Termite Treatment'),
  ('Foundations - Turn-Key'),
  ('Pool Deck - Turn Key'),
  ('Masonry'),
  ('Brick Veneer - Turn-Key'),
  ('Block - Turn Key'),
  ('Stone Vendor - Turn Key'),
  ('Structural Steel'),
  ('Stairs'),
  ('Railings'),
  ('Gates'),
  ('Dog Wash Gate'),
  ('Trash Compactor Gates'),
  ('Electrical Coral Gates'),
  ('Structural Steel - Misc'),
  ('Pre-Engineered Steel Pckg.'),
  ('Steel Engineered Labor'),
  ('Carpentry'),
  ('Framing Material'),
  ('Framing Hardware'),
  ('Plywood Clips'),
  ('Nails And Fasteners'),
  ('Framing Labor'),
  ('Floor Truss Package'),
  ('Roof Truss Package'),
  ('Siding and Boxing'),
  ('Porch Railings'),
  ('Thermal'),
  ('Insulation'),
  ('Roofing - Turn Key'),
  ('Gutters'),
  ('Doors/Windows'),
  ('Exterior Doors'),
  ('Windows'),
  ('Window & Door Install Mtl.'),
  ('NP1 Sealants'),
  ('Windows/Door Flashing Tape'),
  ('Storefronts'),
  ('Garage Doors/Overhead Doors'),
  ('Attic Hatches'),
  ('Roof Draft Stop Doors'),
  ('Finishes'),
  ('Drywall Turn-Key'),
  ('Ext Drywall (Breezeway) Mtl.'),
  ('Acoustic Ceilings'),
  ('Paint - Interior'),
  ('Exterior Paint/Pressure Washing'),
  ('Wire Shelving'),
  ('Bath Hardware'),
  ('Flooring - Turn-Key'),
  ('Interior Trim - Turn-Key'),
  ('Interior Trim - Labor'),
  ('Interior Trim - Materials'),
  ('Cabinets - Turn-Key'),
  ('Cabinets - Material Only'),
  ('Cabinets - Labor Only'),
  ('Granite Kitchen Tops - Mtl.'),
  ('Granite Bath Tops - Mtl.'),
  ('Granite Kitchen Tops - Lab'),
  ('Granite Bath Tops - Labor'),
  ('Mirrors'),
  ('Blinds'),
  ('Door Hardware'),
  ('Temp Locks'),
  ('Exterior Lock Sets'),
  ('Interior Lock Sets'),
  ('Specialties'),
  ('Awnings'),
  ('Flag Pole'),
  ('Mailboxes'),
  ('Rent Drop Box'),
  ('Dog Wash Station'),
  ('Knox Box'),
  ('Bath Partitions'),
  ('Fire Extinguishers'),
  ('Signage'),
  ('Furnishings'),
  ('Appliances')
) as t(name)
on conflict (category_id, name) do nothing;
